// Flexi Device — device catalog. Sizes are CSS-pixel viewports.
// type: phone | tablet | laptop · os: ios | android | desktop
// cutout: island | notch | punch | none · tag: flagship | top | null
globalThis.FLEXI_DEVICES = globalThis.FLEXI_DEVICES || [
  // ------------------------------------------------------------- Apple
  { id: 'iphone-17-pro-max', brand: 'Apple', name: 'iPhone 17 Pro Max', short: '17 PM', w: 440, h: 956, type: 'phone', os: 'ios', cutout: 'island', year: 2025, tag: 'flagship' },
  { id: 'iphone-17-pro',     brand: 'Apple', name: 'iPhone 17 Pro',     short: '17 Pro', w: 402, h: 874, type: 'phone', os: 'ios', cutout: 'island', year: 2025, tag: 'top' },
  { id: 'iphone-17',         brand: 'Apple', name: 'iPhone 17',         short: '17', w: 402, h: 874, type: 'phone', os: 'ios', cutout: 'island', year: 2025 },
  { id: 'iphone-air',        brand: 'Apple', name: 'iPhone Air',        short: 'Air', w: 420, h: 912, type: 'phone', os: 'ios', cutout: 'island', year: 2025 },
  { id: 'iphone-17e',        brand: 'Apple', name: 'iPhone 17e',        short: '17e', w: 390, h: 844, type: 'phone', os: 'ios', cutout: 'island', year: 2026 },
  { id: 'iphone-16-pro-max', brand: 'Apple', name: 'iPhone 16 Pro Max', short: '16 PM', w: 440, h: 956, type: 'phone', os: 'ios', cutout: 'island', year: 2024, tag: 'flagship' },
  { id: 'iphone-16-pro',     brand: 'Apple', name: 'iPhone 16 Pro',     short: '16 Pro', w: 402, h: 874, type: 'phone', os: 'ios', cutout: 'island', year: 2024, tag: 'top' },
  { id: 'iphone-16-plus',    brand: 'Apple', name: 'iPhone 16 Plus',    short: '16+', w: 430, h: 932, type: 'phone', os: 'ios', cutout: 'island', year: 2024 },
  { id: 'iphone-16',         brand: 'Apple', name: 'iPhone 16',         short: '16', w: 393, h: 852, type: 'phone', os: 'ios', cutout: 'island', year: 2024 },
  { id: 'iphone-16e',        brand: 'Apple', name: 'iPhone 16e',        short: '16e', w: 390, h: 844, type: 'phone', os: 'ios', cutout: 'notch', year: 2025 },
  { id: 'iphone-15-pro-max', brand: 'Apple', name: 'iPhone 15 Pro Max', short: '15 PM', w: 430, h: 932, type: 'phone', os: 'ios', cutout: 'island', year: 2023 },
  { id: 'iphone-15-pro',     brand: 'Apple', name: 'iPhone 15 Pro',     short: '15 Pro', w: 393, h: 852, type: 'phone', os: 'ios', cutout: 'island', year: 2023 },
  { id: 'iphone-15-plus',    brand: 'Apple', name: 'iPhone 15 Plus',    short: '15+', w: 430, h: 932, type: 'phone', os: 'ios', cutout: 'island', year: 2023 },
  { id: 'iphone-15',         brand: 'Apple', name: 'iPhone 15',         short: '15', w: 393, h: 852, type: 'phone', os: 'ios', cutout: 'island', year: 2023 },
  { id: 'iphone-14-pro-max', brand: 'Apple', name: 'iPhone 14 Pro Max', short: '14 PM', w: 430, h: 932, type: 'phone', os: 'ios', cutout: 'island', year: 2022 },
  { id: 'iphone-14-pro',     brand: 'Apple', name: 'iPhone 14 Pro',     short: '14 Pro', w: 393, h: 852, type: 'phone', os: 'ios', cutout: 'island', year: 2022 },
  { id: 'iphone-14-plus',    brand: 'Apple', name: 'iPhone 14 Plus',    short: '14+', w: 428, h: 926, type: 'phone', os: 'ios', cutout: 'notch', year: 2022 },
  { id: 'iphone-14',         brand: 'Apple', name: 'iPhone 13 & 14',    short: '13/14', w: 390, h: 844, type: 'phone', os: 'ios', cutout: 'notch', year: 2022 },
  { id: 'iphone-13-pro-max', brand: 'Apple', name: 'iPhone 13 Pro Max', short: '13 PM', w: 428, h: 926, type: 'phone', os: 'ios', cutout: 'notch', year: 2021 },
  { id: 'iphone-13-mini',    brand: 'Apple', name: 'iPhone 13 mini',    short: '13 mini', w: 375, h: 812, type: 'phone', os: 'ios', cutout: 'notch', year: 2021 },
  { id: 'iphone-12',         brand: 'Apple', name: 'iPhone 12',         short: '12', w: 390, h: 844, type: 'phone', os: 'ios', cutout: 'notch', year: 2020 },
  { id: 'iphone-11-pro-max', brand: 'Apple', name: 'iPhone 11 Pro Max', short: '11 PM', w: 414, h: 896, type: 'phone', os: 'ios', cutout: 'notch', year: 2019 },
  { id: 'iphone-11',         brand: 'Apple', name: 'iPhone 11 / XR',    short: '11', w: 414, h: 896, type: 'phone', os: 'ios', cutout: 'notch', year: 2019 },
  { id: 'iphone-x',          brand: 'Apple', name: 'iPhone X / XS',     short: 'X', w: 375, h: 812, type: 'phone', os: 'ios', cutout: 'notch', year: 2017 },
  { id: 'iphone-se',         brand: 'Apple', name: 'iPhone SE (2022)',  short: 'SE', w: 375, h: 667, type: 'phone', os: 'ios', cutout: 'none', year: 2022, homeButton: true },
  { id: 'iphone-8-plus',     brand: 'Apple', name: 'iPhone 8 Plus',     short: '8+', w: 414, h: 736, type: 'phone', os: 'ios', cutout: 'none', year: 2017, homeButton: true },
  { id: 'ipad-pro-13',       brand: 'Apple', name: 'iPad Pro 13 (M4)',  short: 'Pro 13', w: 1032, h: 1376, type: 'tablet', os: 'ios', cutout: 'none', year: 2024, tag: 'flagship' },
  { id: 'ipad-pro-12',       brand: 'Apple', name: 'iPad Pro 12.9',     short: 'Pro 12.9', w: 1024, h: 1366, type: 'tablet', os: 'ios', cutout: 'none', year: 2022, tag: 'flagship' },
  { id: 'ipad-pro-11',       brand: 'Apple', name: 'iPad Pro 11',       short: 'Pro 11', w: 834, h: 1194, type: 'tablet', os: 'ios', cutout: 'none', year: 2024, tag: 'top' },
  { id: 'ipad-air-13',       brand: 'Apple', name: 'iPad Air 13',       short: 'Air 13', w: 1024, h: 1366, type: 'tablet', os: 'ios', cutout: 'none', year: 2024 },
  { id: 'ipad-air-11',       brand: 'Apple', name: 'iPad Air 11',       short: 'Air 11', w: 820, h: 1180, type: 'tablet', os: 'ios', cutout: 'none', year: 2024 },
  { id: 'ipad-10',           brand: 'Apple', name: 'iPad (10th gen)',   short: 'iPad', w: 820, h: 1180, type: 'tablet', os: 'ios', cutout: 'none', year: 2022 },
  { id: 'ipad-mini',         brand: 'Apple', name: 'iPad mini',         short: 'mini', w: 744, h: 1133, type: 'tablet', os: 'ios', cutout: 'none', year: 2024 },
  { id: 'ipad-9',            brand: 'Apple', name: 'iPad (9th gen)',    short: 'iPad 9', w: 810, h: 1080, type: 'tablet', os: 'ios', cutout: 'none', year: 2021, homeButton: true },
  // ----------------------------------------------------------- Samsung
  { id: 'galaxy-s25-ultra',  brand: 'Samsung', name: 'Galaxy S25 Ultra', short: 'S25 U', w: 384, h: 832, type: 'phone', os: 'android', cutout: 'punch', year: 2025, tag: 'flagship' },
  { id: 'galaxy-s25-plus',   brand: 'Samsung', name: 'Galaxy S25+',      short: 'S25+', w: 384, h: 832, type: 'phone', os: 'android', cutout: 'punch', year: 2025, tag: 'top' },
  { id: 'galaxy-s25',        brand: 'Samsung', name: 'Galaxy S25',       short: 'S25', w: 360, h: 780, type: 'phone', os: 'android', cutout: 'punch', year: 2025 },
  { id: 'galaxy-s24-ultra',  brand: 'Samsung', name: 'Galaxy S24 Ultra', short: 'S24 U', w: 384, h: 824, type: 'phone', os: 'android', cutout: 'punch', year: 2024, tag: 'flagship' },
  { id: 'galaxy-s24',        brand: 'Samsung', name: 'Galaxy S24',       short: 'S24', w: 360, h: 780, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'galaxy-s23',        brand: 'Samsung', name: 'Galaxy S23',       short: 'S23', w: 360, h: 780, type: 'phone', os: 'android', cutout: 'punch', year: 2023 },
  { id: 'galaxy-z-flip-6',   brand: 'Samsung', name: 'Galaxy Z Flip 6',  short: 'Flip 6', w: 360, h: 748, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'galaxy-z-fold-6',   brand: 'Samsung', name: 'Galaxy Z Fold 6 (open)', short: 'Fold 6', w: 768, h: 906, type: 'tablet', os: 'android', cutout: 'none', year: 2024 },
  { id: 'galaxy-a55',        brand: 'Samsung', name: 'Galaxy A55',       short: 'A55', w: 360, h: 800, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'galaxy-a15',        brand: 'Samsung', name: 'Galaxy A15',       short: 'A15', w: 360, h: 800, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'galaxy-tab-s9',     brand: 'Samsung', name: 'Galaxy Tab S9',    short: 'Tab S9', w: 800, h: 1280, type: 'tablet', os: 'android', cutout: 'none', year: 2023 },
  { id: 'galaxy-tab-a9',     brand: 'Samsung', name: 'Galaxy Tab A9+',   short: 'Tab A9', w: 800, h: 1280, type: 'tablet', os: 'android', cutout: 'none', year: 2023 },
  // ------------------------------------------------------------ Google
  { id: 'pixel-10-pro-xl',   brand: 'Google', name: 'Pixel 10 Pro XL',  short: '10 XL', w: 412, h: 928, type: 'phone', os: 'android', cutout: 'punch', year: 2025, tag: 'flagship' },
  { id: 'pixel-10-pro',      brand: 'Google', name: 'Pixel 10 Pro',     short: '10 Pro', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2025, tag: 'top' },
  { id: 'pixel-10',          brand: 'Google', name: 'Pixel 10',         short: '10', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2025 },
  { id: 'pixel-9-pro-xl',    brand: 'Google', name: 'Pixel 9 Pro XL',   short: '9 XL', w: 412, h: 928, type: 'phone', os: 'android', cutout: 'punch', year: 2024, tag: 'flagship' },
  { id: 'pixel-9-pro',       brand: 'Google', name: 'Pixel 9 Pro',      short: '9 Pro', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'pixel-9',           brand: 'Google', name: 'Pixel 9',          short: '9', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'pixel-9a',          brand: 'Google', name: 'Pixel 9a',         short: '9a', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2025 },
  { id: 'pixel-8-pro',       brand: 'Google', name: 'Pixel 8 Pro',      short: '8 Pro', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2023 },
  { id: 'pixel-8',           brand: 'Google', name: 'Pixel 8',          short: '8', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2023 },
  { id: 'pixel-7',           brand: 'Google', name: 'Pixel 7',          short: '7', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2022 },
  { id: 'pixel-tablet',      brand: 'Google', name: 'Pixel Tablet',     short: 'Tab', w: 800, h: 1280, type: 'tablet', os: 'android', cutout: 'none', year: 2023 },
  // ------------------------------------------------------------ Xiaomi
  { id: 'xiaomi-15',         brand: 'Xiaomi', name: 'Xiaomi 15',        short: '15', w: 393, h: 873, type: 'phone', os: 'android', cutout: 'punch', year: 2025, tag: 'flagship' },
  { id: 'xiaomi-14',         brand: 'Xiaomi', name: 'Xiaomi 14',        short: '14', w: 393, h: 873, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'redmi-note-14',     brand: 'Xiaomi', name: 'Redmi Note 14',    short: 'N14', w: 393, h: 873, type: 'phone', os: 'android', cutout: 'punch', year: 2025 },
  { id: 'redmi-note-13',     brand: 'Xiaomi', name: 'Redmi Note 13',    short: 'N13', w: 393, h: 873, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'poco-x7',           brand: 'Xiaomi', name: 'POCO X7',          short: 'X7', w: 393, h: 873, type: 'phone', os: 'android', cutout: 'punch', year: 2025 },
  // ---------------------------------------------------------- Motorola
  { id: 'moto-edge-50',      brand: 'Motorola', name: 'Moto Edge 50',    short: 'E50', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2024, tag: 'top' },
  { id: 'moto-razr-50',      brand: 'Motorola', name: 'Moto Razr 50',    short: 'Razr', w: 412, h: 924, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'moto-g85',          brand: 'Motorola', name: 'Moto G85',        short: 'G85', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'moto-g54',          brand: 'Motorola', name: 'Moto G54',        short: 'G54', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2023 },
  { id: 'moto-g24',          brand: 'Motorola', name: 'Moto G24',        short: 'G24', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  // ----------------------------------------------------------- OnePlus
  { id: 'oneplus-13',        brand: 'OnePlus', name: 'OnePlus 13',       short: '13', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2025, tag: 'flagship' },
  { id: 'oneplus-12',        brand: 'OnePlus', name: 'OnePlus 12',       short: '12', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'oneplus-nord-4',    brand: 'OnePlus', name: 'OnePlus Nord 4',   short: 'Nord', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  // ------------------------------------------------------------ Others
  { id: 'huawei-p60',        brand: 'Huawei', name: 'Huawei P60 Pro',    short: 'P60', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2023 },
  { id: 'oppo-find-x8',      brand: 'OPPO',   name: 'OPPO Find X8',      short: 'X8', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'vivo-x200',         brand: 'vivo',   name: 'vivo X200',         short: 'X200', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2024 },
  { id: 'nothing-phone-3',   brand: 'Nothing', name: 'Nothing Phone (3)', short: '(3)', w: 412, h: 915, type: 'phone', os: 'android', cutout: 'punch', year: 2025 },
  // ---------------------------------------------------- Laptops / desktop
  { id: 'macbook-air-13',    brand: 'Laptops', name: 'MacBook Air 13',   short: 'MBA', w: 1470, h: 956, type: 'laptop', os: 'desktop', cutout: 'none', year: 2024, tag: 'top' },
  { id: 'macbook-pro-14',    brand: 'Laptops', name: 'MacBook Pro 14',   short: 'MBP', w: 1512, h: 982, type: 'laptop', os: 'desktop', cutout: 'none', year: 2024 },
  { id: 'macbook-pro-16',    brand: 'Laptops', name: 'MacBook Pro 16',   short: 'MBP16', w: 1728, h: 1117, type: 'laptop', os: 'desktop', cutout: 'none', year: 2024 },
  { id: 'laptop-hd',         brand: 'Laptops', name: 'Laptop HD',        short: 'HD', w: 1366, h: 768, type: 'laptop', os: 'desktop', cutout: 'none', year: 2020 },
  { id: 'laptop-fhd',        brand: 'Laptops', name: 'Laptop Full HD',   short: 'FHD', w: 1920, h: 1080, type: 'laptop', os: 'desktop', cutout: 'none', year: 2020 },
  { id: 'desktop-qhd',       brand: 'Laptops', name: 'Desktop QHD',      short: 'QHD', w: 2560, h: 1440, type: 'laptop', os: 'desktop', cutout: 'none', year: 2020 },
];
